In [1]:
import warnings

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split
)

from sklearn.metrics import mean_absolute_error

from lazypredict.Supervised import LazyRegressor

# **Config**
---

In [2]:
random_seed = 12354
sns.set(style="darkgrid")
sns.set(font_scale=1)
pd.set_option('display.float_format', '{:,.5f}'.format)
title_data = 'Temperature prediction'
paleta = sns.color_palette("tab10").as_hex()
warnings.filterwarnings("ignore")

In [15]:
wra_regressor = LazyRegressor(
    verbose=0,
    ignore_warnings=True, 
    custom_metric=mean_absolute_error, 
    predictions=True, 
    regressors ='all' )

# **Data First Strategy**
---

In [3]:
data_first = pd.read_csv('../data/first_strategy.csv')

**Split**

In [4]:
X = data_first[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue'
]]

y = data_first['temperature_sum']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

In [8]:
regressor_model_first_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 42/42 [00:05<00:00,  7.56it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000127 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 2731, number of used features: 4
[LightGBM] [Info] Start training from score 6492.621384

In [ ]:
GradientBoostingRegressor
AdaBoostRegressor
HistGradientBoostingRegressor
DummyRegressor
RandomForestRegressor
XGBRegressor

In [10]:
regressor_model_first_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
GradientBoostingRegressor,0.01136,0.01957,"3,444.53929",0.37844,"2,664.34082"
OrthogonalMatchingPursuit,0.03432,0.04233,"3,404.31949",0.00868,"2,695.19192"
GammaRegressor,0.04228,0.05023,"3,390.25055",0.01043,"2,705.52161"
AdaBoostRegressor,-0.00980,-0.00142,"3,481.21416",0.05836,"2,715.79042"
HistGradientBoostingRegressor,-0.01366,-0.00525,"3,487.86675",0.15253,"2,743.51814"
LGBMRegressor,-0.01459,-0.00617,"3,489.46143",0.06161,"2,763.08134"
SVR,-0.00782,0.00054,"3,477.80063",0.26304,"2,776.24835"
NuSVR,-0.00745,0.00091,"3,477.16173",0.17819,"2,776.52756"
QuantileRegressor,-0.01237,-0.00397,"3,485.63828",0.18304,"2,784.07039"
DummyRegressor,-0.01833,-0.00988,"3,495.88260",0.00608,"2,802.49959"
RandomForestRegressor,-0.07431,-0.06539,"3,590.68488",1.16106,"2,844.29414"
XGBRegressor,-0.11609,-0.10682,"3,659.83911",0.15220,"2,885.09596"
ExtraTreesRegressor,-0.10450,-0.09533,"3,640.79197",0.35679,"2,888.06509"
BaggingRegressor,-0.14521,-0.13570,"3,707.27540",0.12134,"2,908.42650"
ElasticNet,-2.35962,-2.33174,"6,349.76968",0.00524,"2,924.20678"
PassiveAggressiveRegressor,-3.16339,-3.12884,"7,068.64766",0.01930,"2,939.83891"
ElasticNetCV,-2.43254,-2.40405,"6,418.31193",0.04732,"2,941.78841"
TweedieRegressor,-2.42907,-2.40061,"6,415.06220",0.00841,"2,942.10272"
KNeighborsRegressor,-0.17249,-0.16276,"3,751.17825",0.00937,"2,994.97308"
SGDRegressor,-6.85321,-6.78804,"9,708.15336",0.01731,"3,068.73480"
HuberRegressor,-10.53486,-10.43914,"11,765.73894",0.01429,"3,169.39910"
BayesianRidge,-19.64956,-19.47819,"15,742.30654",0.00631,"3,349.75236"
Lasso,-24.84290,-24.62844,"17,610.98433",0.01761,"3,436.74476"
LassoLars,-24.88080,-24.66602,"17,623.89366",0.00883,"3,437.34198"
LassoCV,-24.89152,-24.67666,"17,627.54395",0.08491,"3,437.51819"
Ridge,-25.90380,-25.68053,"17,968.82952",0.02220,"3,453.46034"
RidgeCV,-25.90380,-25.68053,"17,968.82952",0.03147,"3,453.46034"
TransformedTargetRegressor,-26.97378,-26.74164,"18,322.66365",0.00978,"3,469.99818"
LinearRegression,-26.97378,-26.74164,"18,322.66365",0.00524,"3,469.99818"
OrthogonalMatchingPursuitCV,-26.97378,-26.74164,"18,322.66365",0.01250,"3,469.99818"
Lars,-26.97378,-26.74164,"18,322.66365",0.00810,"3,469.99818"
LarsCV,-26.97378,-26.74164,"18,322.66365",0.01343,"3,469.99818"
LassoLarsIC,-26.97378,-26.74164,"18,322.66365",0.00855,"3,469.99818"
LassoLarsCV,-26.97378,-26.74164,"18,322.66365",0.01427,"3,469.99818"
ExtraTreeRegressor,-1.02435,-1.00755,"4,928.96037",0.01022,"3,809.82816"
DecisionTreeRegressor,-1.18069,-1.16260,"5,115.76096",0.02336,"3,892.65631"
LinearSVR,-1.70904,-1.68656,"5,701.91766",0.00797,"4,533.67582"
MLPRegressor,-22.49006,-22.29513,"16,790.17003",0.69880,"5,006.95840"
KernelRidge,-28.18505,-27.94285,"18,715.14565",0.42134,"6,959.16401"
RANSACRegressor,"-5,048.56886","-5,006.66372","246,172.84489",0.05987,"14,405.66002"
GaussianProcessRegressor,"-462,460.50149","-458,622.64671","2,355,867.10236",0.83569,"254,577.49163"
PoissonRegressor,"-4,076,762,559,013,475,140,585,770,618,757,323,...","-4,042,930,504,581,828,318,679,602,175,112,250,...","6,994,725,956,439,352,351,752,454,144.00000",0.01255,"318,271,051,343,936,037,517,787,136.00000"

# **Data Second Strategy**
---

In [11]:
data_second = pd.read_csv('../data/second_strategy.csv')

In [12]:
data_second

,key,temperature_sum,active_power_sum,reactive_power_sum,minutes_process_sum,gas_purgue,C1,C2,C3
0,1,"8,007.00000",4.87815,3.18324,18.30000,29.74999,20.66459,-39.52270,-28.69459
1,10,"12,678.00000",2.92362,2.49612,13.74900,6.52989,22.22047,-63.83044,16.63654
2,100,"6,295.00000",4.43513,3.15134,17.71700,12.64319,20.94804,-26.35074,-21.89425
3,1000,"9,575.00000",1.40241,0.93353,6.75100,9.80073,-251.22053,4.11963,158.15935
4,1001,"14,293.00000",4.24727,3.37764,18.86600,19.67891,-253.90412,-18.30161,114.97372
...,...,...,...,...,...,...,...,...,...
3209,995,"9,542.00000",1.90945,1.48719,8.85000,12.30884,-3.19796,-97.93836,-16.53886
3210,996,"7,986.00000",1.19491,0.89953,8.23300,8.83820,7.08725,-105.39740,-32.67329
3211,997,"4,762.00000",1.93813,1.56647,10.11700,7.48937,-13.82826,-46.86487,-13.20168
3212,998,"9,482.00000",2.17320,1.51996,9.48300,4.22033,-254.64611,-104.83379,5.76944
3213,999,"6,375.00000",1.97664,1.45589,10.88300,14.07026,-8.08360,36.43761,131.87718

In [16]:
X = data_second[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue', 'C1', 'C2', 'C3'
]]

y = data_second['temperature_sum']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.85,
    shuffle=True,
    random_state=random_seed
)

In [19]:
regressor_model_second_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 42/42 [00:06<00:00,  6.79it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000102 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 2731, number of used features: 7
[LightGBM] [Info] Start training from score 6492.621384

In [21]:
regressor_model_second_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
OrthogonalMatchingPursuitCV,0.03759,0.05157,"3,387.86135",0.01029,"2,651.02085"
OrthogonalMatchingPursuit,0.02822,0.04233,"3,404.31949",0.00844,"2,695.19192"
RandomForestRegressor,-0.00781,0.00683,"3,466.85156",1.74138,"2,696.51344"
KNeighborsRegressor,-0.01389,0.00084,"3,477.29110",0.01152,"2,699.72588"
GradientBoostingRegressor,-0.03353,-0.01852,"3,510.81320",0.60625,"2,701.88038"
GammaRegressor,0.03662,0.05062,"3,389.56180",0.00873,"2,706.20187"
HistGradientBoostingRegressor,0.00319,0.01767,"3,447.87981",0.15628,"2,709.33345"
LGBMRegressor,-0.01546,-0.00072,"3,479.99158",0.05825,"2,715.69431"
ExtraTreesRegressor,-0.00808,0.00656,"3,467.30850",0.46335,"2,729.30139"
SVR,-0.01528,-0.00054,"3,479.67963",0.19475,"2,778.30082"
NuSVR,-0.01510,-0.00036,"3,479.37385",0.15138,"2,778.43567"
QuantileRegressor,-0.01876,-0.00397,"3,485.63828",0.18389,"2,784.07039"
DummyRegressor,-0.02476,-0.00988,"3,495.88260",0.00741,"2,802.49959"
AdaBoostRegressor,-0.11383,-0.09765,"3,644.63893",0.14469,"2,808.44104"
BaggingRegressor,-0.08850,-0.07269,"3,602.95870",0.18138,"2,820.87184"
XGBRegressor,-0.18019,-0.16305,"3,751.64318",0.18645,"2,903.63780"
ElasticNet,-2.69156,-2.63795,"6,635.15256",0.00542,"2,938.53681"
ElasticNetCV,-2.58265,-2.53062,"6,536.54175",0.04561,"2,948.22789"
TweedieRegressor,-2.57563,-2.52370,"6,530.13497",0.00729,"2,948.41854"
PassiveAggressiveRegressor,-3.86591,-3.79524,"7,617.77136",0.01224,"2,965.69259"
SGDRegressor,-11.70982,-11.52524,"12,311.63102",0.01062,"3,195.78940"
HuberRegressor,-14.09683,-13.87758,"13,418.02951",0.01742,"3,235.43882"
BayesianRidge,-19.25499,-18.96083,"15,542.17891",0.00684,"3,339.92143"
Lasso,-33.94217,-33.43471,"20,413.65519",0.00925,"3,563.42078"
LassoLars,-33.98568,-33.47758,"20,426.36006",0.00759,"3,564.01102"
LassoCV,-34.00097,-33.49266,"20,430.82392",0.07504,"3,564.21766"
Ridge,-35.13847,-34.61364,"20,760.16160",0.00764,"3,579.58714"
RidgeCV,-35.13847,-34.61364,"20,760.16160",0.00676,"3,579.58714"
TransformedTargetRegressor,-36.51529,-35.97046,"21,151.93061",0.00709,"3,597.73865"
LinearRegression,-36.51529,-35.97046,"21,151.93061",0.00734,"3,597.73865"
Lars,-36.51529,-35.97046,"21,151.93061",0.01071,"3,597.73865"
LarsCV,-36.51529,-35.97046,"21,151.93061",0.01766,"3,597.73865"
LassoLarsIC,-36.51529,-35.97046,"21,151.93061",0.01065,"3,597.73865"
LassoLarsCV,-36.51529,-35.97046,"21,151.93061",0.01328,"3,597.73865"
ExtraTreeRegressor,-1.06125,-1.03131,"4,958.05212",0.01058,"3,783.08903"
DecisionTreeRegressor,-1.07613,-1.04598,"4,975.92111",0.03185,"3,801.78675"
LinearSVR,-1.72033,-1.68082,"5,695.82616",0.00966,"4,532.57692"
MLPRegressor,-20.41458,-20.10358,"15,980.87850",0.75401,"4,908.35478"
RANSACRegressor,-171.17659,-168.67610,"45,314.05235",0.06243,"6,175.48951"
KernelRidge,-37.27523,-36.71937,"21,365.09218",0.34570,"7,072.19667"
GaussianProcessRegressor,-74.24490,-73.15213,"29,956.03796",0.53922,"19,398.64841"
PoissonRegressor,"-9,406,005,854,851,068,861,773,065,254,160,264,...","-9,269,404,110,071,074,372,049,931,351,938,498,...","334,925,700,287,984,342,782,825,923,084,288.00000",0.01057,"15,239,647,045,017,873,342,229,844,590,592.00000"

# **Data Third Strategy**
---

In [22]:
data_third = pd.read_csv('../data/third_strategy.csv')

In [23]:
data_third

,key,temperature_sum,C1,C2,C3,C4,C5
0,1,"8,007.00000",20.88850,-39.17555,-28.85761,29.09527,-22.80295
1,10,"12,678.00000",22.18162,-63.91922,16.61842,59.46159,-69.01695
2,100,"6,295.00000",21.03320,-26.25830,-21.93474,31.55612,-36.21207
3,1000,"9,575.00000",-251.30467,3.99810,158.15087,-53.95510,43.78298
4,1001,"14,293.00000",-253.70081,-18.05334,114.83498,-55.43850,14.96360
...,...,...,...,...,...,...,...
3209,995,"9,542.00000",-3.27465,-97.94387,-16.63067,-5.72901,50.51911
3210,996,"7,986.00000",6.96749,-105.44653,-32.75088,9.37505,77.10562
3211,997,"4,762.00000",-13.91689,-46.96295,-13.19838,-29.78941,-63.18561
3212,998,"9,482.00000",-254.73121,-104.84294,5.68684,-38.86811,15.45676
3213,999,"6,375.00000",-8.10456,36.32399,131.89901,-37.58493,12.04590

In [25]:
X = data_third[[
    "C1", "C2", "C3", "C4", "C5"
]]

y = data_third['temperature_sum']

In [26]:
regressor_model_third_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 42/42 [00:06<00:00,  6.17it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000078 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 2731, number of used features: 7
[LightGBM] [Info] Start training from score 6492.621384

In [27]:
regressor_model_third_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
OrthogonalMatchingPursuitCV,0.03759,0.05157,"3,387.86135",0.00893,"2,651.02085"
OrthogonalMatchingPursuit,0.02822,0.04233,"3,404.31949",0.00849,"2,695.19192"
RandomForestRegressor,-0.00781,0.00683,"3,466.85156",1.79089,"2,696.51344"
KNeighborsRegressor,-0.01389,0.00084,"3,477.29110",0.01274,"2,699.72588"
GradientBoostingRegressor,-0.03353,-0.01852,"3,510.81320",0.62270,"2,701.88038"
GammaRegressor,0.03662,0.05062,"3,389.56180",0.01100,"2,706.20187"
HistGradientBoostingRegressor,0.00319,0.01767,"3,447.87981",0.18060,"2,709.33345"
LGBMRegressor,-0.01546,-0.00072,"3,479.99158",0.06142,"2,715.69431"
ExtraTreesRegressor,-0.00808,0.00656,"3,467.30850",0.51762,"2,729.30139"
SVR,-0.01528,-0.00054,"3,479.67963",0.25491,"2,778.30082"
NuSVR,-0.01510,-0.00036,"3,479.37385",0.14653,"2,778.43567"
QuantileRegressor,-0.01876,-0.00397,"3,485.63828",0.19154,"2,784.07039"
DummyRegressor,-0.02476,-0.00988,"3,495.88260",0.00507,"2,802.49959"
AdaBoostRegressor,-0.11383,-0.09765,"3,644.63893",0.15064,"2,808.44104"
BaggingRegressor,-0.08850,-0.07269,"3,602.95870",0.19048,"2,820.87184"
XGBRegressor,-0.18019,-0.16305,"3,751.64318",0.24580,"2,903.63780"
ElasticNet,-2.69156,-2.63795,"6,635.15256",0.00909,"2,938.53681"
ElasticNetCV,-2.58265,-2.53062,"6,536.54175",0.05362,"2,948.22789"
TweedieRegressor,-2.57563,-2.52370,"6,530.13497",0.01362,"2,948.41854"
PassiveAggressiveRegressor,-3.86591,-3.79524,"7,617.77136",0.01410,"2,965.69259"
SGDRegressor,-11.70982,-11.52524,"12,311.63102",0.01471,"3,195.78940"
HuberRegressor,-14.09683,-13.87758,"13,418.02951",0.01536,"3,235.43882"
BayesianRidge,-19.25499,-18.96083,"15,542.17891",0.01053,"3,339.92143"
Lasso,-33.94217,-33.43471,"20,413.65519",0.00986,"3,563.42078"
LassoLars,-33.98568,-33.47758,"20,426.36006",0.00861,"3,564.01102"
LassoCV,-34.00097,-33.49266,"20,430.82392",0.07678,"3,564.21766"
Ridge,-35.13847,-34.61364,"20,760.16160",0.01062,"3,579.58714"
RidgeCV,-35.13847,-34.61364,"20,760.16160",0.00749,"3,579.58714"
TransformedTargetRegressor,-36.51529,-35.97046,"21,151.93061",0.01413,"3,597.73865"
LinearRegression,-36.51529,-35.97046,"21,151.93061",0.00657,"3,597.73865"
Lars,-36.51529,-35.97046,"21,151.93061",0.00874,"3,597.73865"
LarsCV,-36.51529,-35.97046,"21,151.93061",0.02447,"3,597.73865"
LassoLarsIC,-36.51529,-35.97046,"21,151.93061",0.00981,"3,597.73865"
LassoLarsCV,-36.51529,-35.97046,"21,151.93061",0.01303,"3,597.73865"
ExtraTreeRegressor,-1.06125,-1.03131,"4,958.05212",0.01559,"3,783.08903"
DecisionTreeRegressor,-1.07613,-1.04598,"4,975.92111",0.03351,"3,801.78675"
LinearSVR,-1.72033,-1.68082,"5,695.82616",0.00776,"4,532.57692"
MLPRegressor,-20.41458,-20.10358,"15,980.87850",0.80725,"4,908.35478"
RANSACRegressor,-171.17659,-168.67610,"45,314.05235",0.07462,"6,175.48951"
KernelRidge,-37.27523,-36.71937,"21,365.09218",0.37013,"7,072.19667"
GaussianProcessRegressor,-74.24490,-73.15213,"29,956.03796",0.74118,"19,398.64841"
PoissonRegressor,"-9,406,005,854,851,068,861,773,065,254,160,264,...","-9,269,404,110,071,074,372,049,931,351,938,498,...","334,925,700,287,984,342,782,825,923,084,288.00000",0.00939,"15,239,647,045,017,873,342,229,844,590,592.00000"

# **Data Fourth Strategy**
---

In [28]:
data_fourth = pd.read_csv('../data/fourth_strategy.csv')

In [30]:
data_fourth.columns

Index(['key', 'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
       'gas_purgue', 'temperature_sum', 'wire_1', 'bulk_12', 'bulk_14',
       'bulk_15'],
      dtype='object')

In [32]:
X = data_fourth[[
    'active_power_sum', 'reactive_power_sum', 'minutes_process_sum',
    'gas_purgue', 'temperature_sum', 'wire_1', 'bulk_12', 'bulk_14',
    'bulk_15'
]]

y = data_fourth['temperature_sum']

In [33]:
regressor_model_fourth_strategy , predictions  = wra_regressor.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

'tuple' object has no attribute '__name__'
Invalid Regressor(s)

100%|██████████| 42/42 [00:06<00:00,  6.56it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000102 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1785
[LightGBM] [Info] Number of data points in the train set: 2731, number of used features: 7
[LightGBM] [Info] Start training from score 6492.621384

In [34]:
regressor_model_fourth_strategy.sort_values('mean_absolute_error')

,Adjusted R-Squared,R-Squared,RMSE,Time Taken,mean_absolute_error
Model,,,,,
OrthogonalMatchingPursuitCV,0.03759,0.05157,"3,387.86135",0.01090,"2,651.02085"
OrthogonalMatchingPursuit,0.02822,0.04233,"3,404.31949",0.00909,"2,695.19192"
RandomForestRegressor,-0.00781,0.00683,"3,466.85156",1.72319,"2,696.51344"
KNeighborsRegressor,-0.01389,0.00084,"3,477.29110",0.01177,"2,699.72588"
GradientBoostingRegressor,-0.03353,-0.01852,"3,510.81320",0.60668,"2,701.88038"
GammaRegressor,0.03662,0.05062,"3,389.56180",0.00756,"2,706.20187"
HistGradientBoostingRegressor,0.00319,0.01767,"3,447.87981",0.17838,"2,709.33345"
LGBMRegressor,-0.01546,-0.00072,"3,479.99158",0.06154,"2,715.69431"
ExtraTreesRegressor,-0.00808,0.00656,"3,467.30850",0.48225,"2,729.30139"
SVR,-0.01528,-0.00054,"3,479.67963",0.21722,"2,778.30082"
NuSVR,-0.01510,-0.00036,"3,479.37385",0.14371,"2,778.43567"
QuantileRegressor,-0.01876,-0.00397,"3,485.63828",0.18323,"2,784.07039"
DummyRegressor,-0.02476,-0.00988,"3,495.88260",0.00791,"2,802.49959"
AdaBoostRegressor,-0.11383,-0.09765,"3,644.63893",0.17474,"2,808.44104"
BaggingRegressor,-0.08850,-0.07269,"3,602.95870",0.18659,"2,820.87184"
XGBRegressor,-0.18019,-0.16305,"3,751.64318",0.19093,"2,903.63780"
ElasticNet,-2.69156,-2.63795,"6,635.15256",0.00844,"2,938.53681"
ElasticNetCV,-2.58265,-2.53062,"6,536.54175",0.06289,"2,948.22789"
TweedieRegressor,-2.57563,-2.52370,"6,530.13497",0.00902,"2,948.41854"
PassiveAggressiveRegressor,-3.86591,-3.79524,"7,617.77136",0.01435,"2,965.69259"
SGDRegressor,-11.70982,-11.52524,"12,311.63102",0.01425,"3,195.78940"
HuberRegressor,-14.09683,-13.87758,"13,418.02951",0.01735,"3,235.43882"
BayesianRidge,-19.25499,-18.96083,"15,542.17891",0.00855,"3,339.92143"
Lasso,-33.94217,-33.43471,"20,413.65519",0.00963,"3,563.42078"
LassoLars,-33.98568,-33.47758,"20,426.36006",0.00648,"3,564.01102"
LassoCV,-34.00097,-33.49266,"20,430.82392",0.07424,"3,564.21766"
Ridge,-35.13847,-34.61364,"20,760.16160",0.00904,"3,579.58714"
RidgeCV,-35.13847,-34.61364,"20,760.16160",0.00774,"3,579.58714"
TransformedTargetRegressor,-36.51529,-35.97046,"21,151.93061",0.00894,"3,597.73865"
LinearRegression,-36.51529,-35.97046,"21,151.93061",0.00718,"3,597.73865"
Lars,-36.51529,-35.97046,"21,151.93061",0.00873,"3,597.73865"
LarsCV,-36.51529,-35.97046,"21,151.93061",0.01933,"3,597.73865"
LassoLarsIC,-36.51529,-35.97046,"21,151.93061",0.00843,"3,597.73865"
LassoLarsCV,-36.51529,-35.97046,"21,151.93061",0.01494,"3,597.73865"
ExtraTreeRegressor,-1.06125,-1.03131,"4,958.05212",0.01485,"3,783.08903"
DecisionTreeRegressor,-1.07613,-1.04598,"4,975.92111",0.03642,"3,801.78675"
LinearSVR,-1.72033,-1.68082,"5,695.82616",0.00558,"4,532.57692"
MLPRegressor,-20.41458,-20.10358,"15,980.87850",0.77098,"4,908.35478"
RANSACRegressor,-171.17659,-168.67610,"45,314.05235",0.06167,"6,175.48951"
KernelRidge,-37.27523,-36.71937,"21,365.09218",0.40296,"7,072.19667"
GaussianProcessRegressor,-74.24490,-73.15213,"29,956.03796",0.57585,"19,398.64841"
PoissonRegressor,"-9,406,005,854,851,068,861,773,065,254,160,264,...","-9,269,404,110,071,074,372,049,931,351,938,498,...","334,925,700,287,984,342,782,825,923,084,288.00000",0.00936,"15,239,647,045,017,873,342,229,844,590,592.00000"